files:
  upload:
    baseDir: /home/anatoly/img

spring:
  datasource:
    url: jdbc:postgresql://localhost/test_database
    username: test_user
    password: qwerty
    driver-class-name: org.postgresql.Driver

  http:
    multipart:
      enabled: false

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB


spring.jpa:
  show-sql: true
  properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  properties.hibernate.temp.use_jdbc_metadata_defaults: false
  hibernate.ddl-auto: none
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d{dd.MM.yyyy HH:mm:ss.SSS} %clr(%-5p) %clr(${PID}){magenta} --- [%20.20t] %clr(%-40.40logger{35}){cyan} %clr([%-4L]){blue} %clr(:){red} %m%n"

#sping.flyway:
#  baseline-on-migrate: false
#  baseline-version: 0.0.1
#  enabled: true
#  locations:
#  - classpath:db/migration
#  - classpath:db/repeatable

